name: TeleHealth Deployment the Client to server 4
on:
  push:
    branches:
      - main
    paths:
      - client/**
      - .github/workflows/client.yml
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: [self-hosted, telehealth]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/telehealth_client:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/telehealth_client:${{ github.run_number }} ./client
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/telehealth_client

      - name: Deploy to Kubernetes
        run: |
          export PATH=$PATH:~.nix-profile/bin:/nix/var/nix/profiles/default/bin
          export IMAGE_TAG=${{ github.run_number }}
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

          kubectl get namespace telehealth || kubectl create namespace telehealth

          for file in client/kube/*; do 
              cat "$file" | envsubst | kubectl apply -f -; 
          done
